spring:
  application:
    name: city-app
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db.changelog/db.changelog-root.xml
    default-schema: public

server:
  servlet:
    context-path: /city/v1

